
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/gb_shop
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG
server:
  hostname: localhost
  port: 8080
mail:
  server:
    host: smtp.beget.com
    port: 25
    username: test@bolshakov.pro
    password: ${hidden.email.password}